// front_vue/src/components/NavBar.vue
<template>
  <div
    class="nav-bar btn-group"
    role="group"
  >
    <button
      class="btn btn-warning disabled retrait-button"
      @click="getMoney"
    >
      <font-awesome-icon icon="money-bill-alt" />
    </button>
    <button
      class="btn btn-success disabled virement-button"
      @click="doTransfert"
    >
      <font-awesome-icon icon="exchange-alt" />
    </button>
    <button
      class="btn btn-primary new-operation-button"
      v-bind="{disabled}"
      @click="addOperation"
    >
      <font-awesome-icon icon="plus" />
    </button>
    <button
      class="btn btn-info operation-recurrente-button"
      @click="getRecurrenteOp"
    >
      <font-awesome-icon icon="retweet" />
    </button>
    <button
      class="btn btn-danger params-button"
      @click="changeParams"
    >
      <font-awesome-icon icon="cogs" />
    </button>
  </div>
</template>

<script>
  import 'mccbng_styles/components/NavBar.scss'

  export default {
    name: 'Navbar',

    computed: {
      disabled () {
        return this.$route.meta.disabledTotalHeader === undefined ? false : this.$route.meta.disabledTotalHeader
      }
    },

    methods: {
      getMoney () {
      },

      addOperation () {
        this.$store.dispatch('toggleAccountList', false)
        this.$router.push('/newOperation')
      },

      doTransfert () {
      },

      getRecurrenteOp () {
        this.$store.dispatch('toggleAccountList', false)
        this.$router.push('/recurrOperation')
      },

      changeParams () {
        this.$store.dispatch('toggleAccountList', false)
        this.$router.push('/config')
      }
    }
  }
</script>

// front_react/src/components/NavBar.jsx
import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import 'mccbng_styles/components/NavBar.scss'
import { Link } from 'react-router-dom'

class NavBar extends React.Component {
  render () {

    return <div className="nav-bar btn-group" role="group">
      <button className="btn btn-warning all-account-button disabled">
        <FontAwesomeIcon icon="list"/>
      </button>
      <button className="btn btn-success virement-button disabled">
        <FontAwesomeIcon icon="exchange-alt"/>
      </button>
      <button className="btn btn-primary new-operation-button disabled">
        <FontAwesomeIcon icon="plus"/>
      </button>
      <button className="btn btn-info operation-recurrente-button disabled">
        <FontAwesomeIcon icon="retweet"/>
      </button>
      <Link className="btn btn-danger params-button" to='/config'>
        <FontAwesomeIcon icon="cogs"/>
      </Link>
    </div>
  }
}

export default NavBar
