// front_react/src/routes/Config.jsx
import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import 'mccbng_styles/routes/Config.scss'

class Config extends React.Component {
  render () {
    return <div className="config">
      <a className="btn btn-info" href="/">
        <FontAwesomeIcon icon="redo"/>
        Reload App
      </a>
    </div>
  }
}

export default Config

// front_vue/src/views/Config.vue
<template>
  <div class="config">
    <a class="btn btn-info" href="/">
      <font-awesome-icon icon="redo"/>
      Reload App
    </a>
  </div>
</template>

<script>
  import 'mccbng_styles/routes/Config.scss'

  export default {
    name: 'Config',

    created () {
      this.$store.commit('setActiveAccount', { NomCompte: 'Configurations' })
    }
  }
</script>
